name: Release Build
on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'
    
jobs:
  Build:
    name: Build/Sign APK
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Get Tag
        id: var
        run: echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT

      - name: Build APK
        id: build
        run: bash ./gradlew assembleRelease
       
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3
        with:
         name: "app-release"
         path: ./app/build/outputs/apk/release/*.apk
         
      - name: Build AAB
        run: bash ./gradlew bundleRelease

      - name: Make artifact
        uses: actions/upload-artifact@v2
        with:
          name: Signed APP Bundle
          path: ${{steps.sign_aab.outputs.signedReleaseFile}}


      - name: Build Changelog
        id: changelog
        uses: ardalanamini/auto-changelog@v3
        with:
          mention-authors: false
          mention-new-contributors: true
          include-compare: true
          semver: false

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref }}
          release_name: Myne ${{ github.ref }}
          draft: true
          body: ${{ steps.changelog.outputs.changelog }} &#x20;
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Upload APK
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{steps.sign_apk.outputs.signedReleaseFile}}
          asset_name: Myne-${{ steps.var.outputs.tag }}.apk
          asset_content_type: application/zip

      - name: Upload AAB
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{steps.sign_aab.outputs.signedReleaseFile}}
          asset_name: Myne-${{ steps.var.outputs.tag }}.aab
          asset_content_type: application/zip
